# Generated by Django 5.2.13 on 2026-04-29 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("child_name", models.CharField(max_length=100)),
                ("child_age", models.CharField(blank=True, max_length=50)),
                (
                    "interests",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of interests"
                    ),
                ),
                (
                    "characters",
                    models.TextField(
                        blank=True,
                        help_text="People to include (names and relationship)",
                    ),
                ),
                (
                    "places",
                    models.TextField(
                        blank=True, help_text="Familiar places to include"
                    ),
                ),
                (
                    "extra_notes",
                    models.TextField(blank=True, help_text="Any other details"),
                ),
                ("content", models.TextField(blank=True)),
                (
                    "tts_voice",
                    models.CharField(
                        choices=[
                            ("alloy", "Alloy (Neutral)"),
                            ("echo", "Echo (Male)"),
                            ("fable", "Fable (Storyteller)"),
                            ("nova", "Nova (Female, Warm)"),
                            ("shimmer", "Shimmer (Female, Bright)"),
                            ("onyx", "Onyx (Male, Deep)"),
                        ],
                        default="fable",
                        max_length=20,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="audio/"),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
